# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'L1_GBVk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireObjectMapper'
  pod 'SwiftKeychainWrapper'
  pod 'RealmSwift'

  # Pods for L1_GBVk

  target 'L1_GBVkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'L1_GBVkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
